config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from .yasg import urlpatterns as doc_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('auth/', include('src.accounts.djoser_token_urls')),

    path('', include('src.accounts.urls')),
    path('', include('src.projects.urls')),
    path('', include('src.main.urls')),
    path('', include('src.tests.urls')),
]

urlpatterns += doc_urls

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path

from . import views
from ..base.services import add_prefix_to_urls

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('password-change/', views.CustomPasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', views.CustomPasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('profiles/<str:slug>/', views.UserDetailView.as_view(),
         name='profile_detail'),
    path('profile/edit/', views.UserEditView.as_view(),
         name='edit_profile'),
    path('profile/invitations/', views.InvitationsView.as_view(),
         name='invitations'),
    path('profile/applies/', views.AppliesView.as_view(),
         name='applies'),
    path('profile/projects/', views.ProjectsView.as_view(),
         name='projects'),
    path('profile/invitations/accept/<int:slot>/', views.accept_invite,
         name='accept_invite'),
    path('profile/invitations/decline/<int:slot>/', views.decline_invite,
         name='decline_invite'),
    path('profile/invitations/retract/<int:slot>/', views.retract_invite,
         name='retract_invite'),
    path('profile/offer/', views.ExecutorOfferFormView.as_view(),
         name='executor_offer'),
    path('profile/delete-offer', views.delete_offer, name='delete_offer'),
    path('workers/', views.ExecutorOfferListView.as_view(), name='offer_list'),
]

# API urls.
api_urlpatterns = [
    path('get-profile/<str:username>/', views.ProfileDetailAPIView.as_view()),
    path('edit-profile/', views.ProfileUpdateAPIView.as_view()),
    path('update-executor-offer/',
         views.ExecutorOfferUpdateAPIView.as_view()),
    path('delete-executor-offer/',
         views.ExecutorOfferDeleteAPIView.as_view()),
    path('change-password/',
         views.ChangePasswordView.as_view()),
    path('get-executor-offers/',
         views.ExecutorOfferListAPIView.as_view()),
    path('get-invited-slots/',
         views.InvitedWorkerSlotListAPIView.as_view()),
    path('get-applied-slots/',
         views.AppliedWorkerSlotListAPIView.as_view()),
    path('accept-invite/<int:slot_id>/',
         views.AcceptInviteAPIView.as_view()),
    path('decline-invite/<int:slot_id>/',
         views.DeclineInviteAPIView.as_view()),
    path('retract-apply/<int:slot_id>/',
         views.RetractInviteAPIView.as_view()),
    path('get-specialiazations/',
         views.SpecializationListAPIView.as_view()),
    path('get-worker-slot/<int:slot_id>/',
         views.WorkerSlotDetailAPIView.as_view()),
]

api_urlpatterns = add_prefix_to_urls(api_urlpatterns)

urlpatterns += api_urlpatterns

src/accounts/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import FileExtensionValidator, MinValueValidator, \
    MaxValueValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from src.projects.models import WorkerSlot, Project
from src.tests.models import BelbinTest, MBTITest, LSQTest


class Specialization(models.Model):
    """
    Specialization db model.
    """

    name = models.CharField('Специализация', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Специализация'
        verbose_name_plural = 'Специализации'


class Status(models.Model):
    """
    Profile status in project db model.
    """

    value = models.CharField('Статус в проекте', max_length=20)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = 'Статус в проекте'
        verbose_name_plural = 'Статусы в проекте'


class Profile(models.Model):
    """
    User's extension db model.
    """

    User._meta.get_field('email')._unique = True
    User._meta.get_field('email').blank = False
    User._meta.get_field('email').null = False

    class RemoteChoices(models.IntegerChoices):
        __empty__ = _('Не указывать')
        ONLINE = 1, _('Онлайн')
        ONLINE_AND_OFFLINE = 2, _('И онлайн, и оффлайн')
        OFFLINE = 3, _('Оффлайн')

    @property
    def remote_value(self):
        if self.remote is None:
            return None
        return self.RemoteChoices.choices[self.remote][1]

    # Sex choices codes:
    MALE = True
    FEMALE = False

    SEX_CHOICES = (
        (None, 'Не указывать'),
        (MALE, 'Мужской'),
        (FEMALE, 'Женский'),
    )

    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                related_name='profile'
                                )

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        if self.user:
            self.user.delete()

    patronymic = models.CharField('Отчество', max_length=30, blank=True,
                                  default='', null=True)
    photo = models.ImageField('Фотография', upload_to='profile_photos/',
                              null=True,
                              blank=True)
    description = models.TextField('Описание',
                                   default='Пользователь не рассказывает о себе',
                                   blank=True
                                   )
    cv = models.FileField('Резюме', upload_to='cvs', null=True, blank=True,
                          validators=[
                              FileExtensionValidator(['pdf', 'docx', 'doc'])])

    belbin = models.ManyToManyField(BelbinTest,
                                    verbose_name='Результат теста по Белбину',
                                    related_name='profiles',
                                    blank=True
                                    )
    mbti = models.ManyToManyField(MBTITest,
                                  verbose_name='Результат теста Майерса-Бриггса',
                                  related_name='profiles',
                                  blank=True
                                  )
    lsq = models.ManyToManyField(LSQTest,
                                 verbose_name='Результат теста Хони-Мамфорда',
                                 related_name='profiles',
                                 blank=True
                                 )

    remote = models.PositiveSmallIntegerField(
        'Удаленная работа',
        choices=RemoteChoices.choices,
        blank=True,
        null=True
    )

    is_male = models.BooleanField('Пол',
                                  choices=SEX_CHOICES,
                                  default=None,
                                  null=True,
                                  blank=True)
    specialization = models.ManyToManyField(Specialization,
                                            verbose_name='Специализация',
                                            blank=True
                                            )
    city = models.CharField('Город', max_length=50, blank=True)
    age = models.PositiveSmallIntegerField('Возраст',
                                           validators=[
                                               MinValueValidator(14),
                                               MaxValueValidator(100)
                                           ],
                                           null=True,
                                           blank=True
                                           )
    verified = models.BooleanField('Подтвержден', default=False)

    def __str__(self):
        return '({username}) {surname} {name} {second_name}' \
            .format(surname=self.user.last_name,
                    name=self.user.first_name,
                    second_name=self.patronymic,
                    username=self.user.username
                    )

    @property
    def sex_value(self):
        if self.is_male is None:
            return None
        if self.is_male:
            return 'Мужской'
        else:
            return 'Женский'

    @property
    def offer(self):
        try:
            return self.executor_offer
        except ObjectDoesNotExist:
            return None

    @property
    def project(self):
        try:
            return self.projects.first()
        except ObjectDoesNotExist:
            return None

    def get_absolute_url(self):
        return reverse('profile_detail', kwargs={'slug': self.user.username})

    def get_invited_slots(self):
        invitations = self.profile_statuses.filter(
            status=Status.objects.get(value='Приглашен')).select_related(
            'worker_slot')
        slots = [relation.worker_slot for relation in invitations]
        return slots

    def get_applied_slots(self):
        applies = self.profile_statuses.filter(
            status=Status.objects.get(value='Ожидает')).select_related(
            'worker_slot')
        slots = [relation.worker_slot for relation in applies]
        return slots

    def get_current_projects(self):
        projects = Project.objects.filter(team__profile_id=self.id)
        return projects

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class ProfileProjectStatus(models.Model):
    """
    Status in project db model.
    """

    worker_slot = models.ForeignKey(WorkerSlot,
                                    verbose_name='Слот работника',
                                    on_delete=models.CASCADE,
                                    related_name='profile_statuses',
                                    null=True
                                    )
    profile = models.ForeignKey(Profile,
                                verbose_name='Профиль',
                                on_delete=models.CASCADE,
                                related_name='profile_statuses',
                                null=True
                                )
    status = models.ForeignKey(Status,
                               verbose_name='Статус',
                               on_delete=models.SET_NULL,
                               related_name='profile_statuses',
                               null=True
                               )

    def __str__(self):
        try:
            return '{username} в проекте {project} имеет статус {status}'.format(
                username=self.profile.user.username,
                project=self.worker_slot.project.title,
                status=self.status.value
            )
        except AttributeError:
            return self.status.value

    class Meta:
        verbose_name = 'Статус вовлеченных в проект пользователей'
        verbose_name_plural = 'Статусы вовлеченных в проект пользователей'


class ExecutorOffer(models.Model):
    """
    Executor offer db model.
    """

    profile = models.OneToOneField(Profile,
                                   on_delete=models.CASCADE,
                                   related_name='executor_offer'
                                   )
    description = models.TextField('Описание')
    salary = models.PositiveIntegerField('Зарплата', null=True, blank=True)
    work_hours = models.PositiveSmallIntegerField('Часы работы в неделю',
                                                  validators=[
                                                      MinValueValidator(1),
                                                      MaxValueValidator(168)
                                                  ],
                                                  default=40
                                                  )

    def __str__(self):
        return 'Карточка {profile}'.format(profile=self.profile.user.username)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Карточка работника'
        verbose_name_plural = 'Карточки работника'

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from src.accounts.models import ExecutorOffer, Profile


class AuthForm(forms.Form):
    """
    Form to log in.
    """

    username = forms.CharField(max_length=30, label='Имя пользователя')
    password = forms.CharField(widget=forms.PasswordInput, label='Пароль')


class RegisterForm(UserCreationForm):
    """
    Registration form.
    """

    email = forms.EmailField(label='Электронный адрес', required=True,
                             widget=forms.EmailInput,
                             help_text='Без него с вами будет невозможно связаться')

    username = forms.CharField(max_length=30, required=True,
                               label='Имя пользователя')
    password1 = forms.CharField(widget=forms.PasswordInput(), label='Пароль')
    password2 = forms.CharField(widget=forms.PasswordInput(),
                                label='Подтвердите пароль')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserEditForm(forms.ModelForm):
    """
    Form which changes user's information.
    """

    email = forms.EmailField(label='Электронный адрес', required=True,
                             widget=forms.EmailInput,
                             help_text='Без него с вами будет невозможно связаться')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    """
    Form which changes profile's information.
    """

    class Meta:
        model = Profile
        exclude = (
            'user', 'verified', 'belbin', 'mbti', 'lsq')


class ExecutorOfferForm(forms.ModelForm):
    """
    Form of creation and changing executor offers.
    """

    salary = forms.IntegerField(label='Ожидаемая зарплата (в рублях)', required=False)

    class Meta:
        model = ExecutorOffer
        exclude = ('profile',)

src/accounts/templates/accounts/applies_list.html
{% extends 'main_base.html' %}
{% block title %}Заявки{% endblock %}
{% block content %}
    <div class="justify-content-center">
        {% if applied_slots %}<h1 class="page-header text-center">
            <b>Ваши заявки</b></h1>
            <div class="row justify-content-md-start">
                {% for slot in applied_slots %}
                    <div class="col-6 card">
                        <div class="card-body">
                            <ul class="list-group text-center">
                                <li class="list-group-item">
                                    <a href="{{ slot.project.get_absolute_url }}">
                                        <button type="button"
                                                class="btn">
                                            {{ slot.project }}
                                        </button>
                                    </a>
                                </li>
                                <li class="list-group-item">
                                    Описание:
                                    <br>
                                    {{ slot.description }}
                                </li>
                                {% if slot.salary %}
                                    <li class="list-group-item">
                                        Получать:
                                        <br>
                                        {{ slot.salary }}
                                    </li>
                                {% endif %}
                                <li class="list-group-item">
                                    Работа
                                    {{ slot.work_hours }}
                                    часов в неделю
                                </li>
                                {% if slot.specialization.exists %}
                                    <li class="list-group-item">
                                        Специализации:
                                        <br>
                                        <ul class="text-center list-group">
                                            {% for spec in slot.specialization.all %}
                                                <li class="list-group-item">{{ spec }}</li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                {% endif %}
                                {% if slot.role.exists %}
                                    <li class="list-group-item">
                                        <br>
                                        Роли по Белбину:
                                        <ul class="text-center list-group">
                                            {% for role in slot.role.all %}
                                                <li class="list-group-item">{{ role }}</li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                {% endif %}
                                <li class="list-group-item">
                                    <form method="post"
                                          action="{% url 'retract_invite' slot=slot.id %}">
                                        {% csrf_token %}
                                        <button type="submit"
                                                class="btn btn-danger">
                                            Отозвать
                                        </button>
                                    </form>
                                </li>
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h1>Пока заявок нет</h1>
        {% endif %}
    </div>
{% endblock %}

src/accounts/templates/accounts/current_projects_list.html
{% extends 'main_base.html' %}
{% block title %}Проекты{% endblock %}
{% block content %}
    <div class="justify-content-center">
        {% if projects %}<h1 class="page-header text-center">
            <b>Ваши проекты</b></h1>
            <div class="row justify-content-md-center">
                <ul class="list-group text-center">
                    {% for project in projects %}
                        <li class="list-group-item">
                            <a href="{{ project.get_absolute_url }}">
                                <button type="button"
                                        class="btn">
                                    {{ project.title }}
                                    <br/>
                                    Электронный адрес владельца:
                                    <br/>
                                    {% if project.owner.user.email %}
                                        {{ project.owner.user.email }}
                                    {% else %}
                                        Не указан
                                    {% endif %}
                                </button>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% else %}
            <h1>Пока проектов нет</h1>
        {% endif %}
    </div>
{% endblock %}

src/accounts/templates/accounts/edit_profile.html
{% extends 'accounts_base.html' %}
{% load crispy_forms_filters %}
{% block title %}Редактировать аккаунт{% endblock %}
{% block card_col %}col-6-lg{% endblock %}
{% block main %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Редактирование профиля</h4>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form_user|crispy }}
                {{ form_profile|crispy }}
                <button type="submit" class="btn btn-primary btn-block">
                    Изменить
                </button>
            </form>
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/executor_offer_form.html
{% extends 'forms_base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}
    Предложение работника
{% endblock %}
{% block main %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Ваше предложение</h4>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-block">
                    Сохранить
                </button>
            </form>
            {% if form.initial %}
                <form style="margin-top: 40px" method="post"
                      action="{% url 'delete_offer' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-block">
                        <b>Удалить</b>
                    </button>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/executor_offer_list.html
{% extends 'main_base.html' %}
{% block title %}Предложения{% endblock %}
{% block sidebar %}
    {% include 'include/executor_filter.html' %}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-md-start">
            {% for offer in executoroffer_list %}
                <div class="col-6 card">
                    <div class="card-body">
                        <ul class="list-group text-center">
                            <li class="list-group-item">
                                <h5>Работник {{ offer.profile }}</h5>
                            </li>
                            <li class="list-group-item">
                                <b>Описание:</b>
                                <br>
                                {{ offer.description }}
                            </li>
                            {% if offer.salary %}
                                <li class="list-group-item">
                                    <b>Рассчитывает получать:</b>
                                    <br>
                                    {{ offer.salary }} рублей
                                </li>
                            {% endif %}
                            <li class="list-group-item">
                                <b>Хочет работать</b>
                                {{ offer.work_hours }}
                                часов в неделю
                            </li>
                            {% if offer.profile.specialization.exists %}
                                <li class="list-group-item">
                                    <b>Специализации:</b>
                                    <br>
                                    <ul class="text-center list-group">
                                        {% for spec in offer.profile.specialization.all %}
                                            <li class="list-group-item">{{ spec }}</li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endif %}
                            {% if offer.profile.belbin.exists %}
                                <li class="list-group-item">
                                    <br>
                                    <b>Роли по Белбину:</b>
                                    <ul class="text-center list-group">
                                        {% for role in offer.profile.belbin.all %}
                                            <li class="list-group-item">{{ role }}</li>
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endif %}
                            <li class="list-group-item">
                                <a href="{{ offer.profile.get_absolute_url }}">
                                    <button type="button"
                                            class="btn btn-primary">
                                        Перейти в профиль
                                    </button>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="bg bg1 text-right mt-4">
            {% include 'include/pagination.html' %}
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/logged_out.html
{% extends 'accounts_base.html' %}
{% block title %}
    Выход
{% endblock %}
{% block main %}
    <div class="card">
        <div style="text-align: center" class="card-body">
            <p>Вы вышли!</p>
            <p><a href="{% url 'login' %}">Зайти
                снова</a></p>
            <p><a href="{% url 'main_page' %}">Главная
                страница</a></p>
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/login.html
{% extends 'accounts_base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}
    Вход
{% endblock %}
{% block main %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Вход в аккаунт</h4>

            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-block">Войти
                </button>
            </form>
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/password_change.html
{% extends 'accounts_base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}
    Смена пароля
{% endblock %}
{% block main %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Смена пароля</h4>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Сменить пароль
                </button>
            </form>
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/password_change_done.html
{% extends 'accounts_base.html' %}
{% block title %}
    Пароль изменен
{% endblock %}
{% block main %}
    <div class="card">
        <div style="text-align: center" class="card-body">
            <p>Пароль успешно изменен!</p>
            <p><a href="{{ user.profile.get_absolute_url }}">Перейти в
                аккаунт</a></p>
            <p><a href="{% url 'main_page' %}">Главная страница</a></p>
        </div>
    </div>
{% endblock %}

src/accounts/templates/accounts/register.html
{% extends 'accounts_base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %}
    Регистрация
{% endblock %}
{% block main %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Регистрация</h4>
            <form method="post">
                {% csrf_token %}
                {{ user_form|crispy }}
                <button type="submit" class="btn btn-primary btn-block">
                    Зарегистрироваться
                </button>
            </form>
        </div>
    </div>
{% endblock %}